spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/emergency_shelter_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET:change-me-to-a-long-random-secret-key}
jwt.expiration-ms=86400000
jwt.header=Authorization
jwt.token-prefix=Bearer 
